<a href="https://colab.research.google.com/github/MEDA-NAVADURGA/CODSOFT/blob/main/IRIS_FLOWER_CLASSIFICATION(task_3).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

IRIS FLOWER CLASSIFICATION:-
============================================
problem statement:-
--------------------
*The Iris flower dataset consists of three species: setosa, versicolor,
and virginica. These species can be distinguished based on their
measurements. Now, imagine that you have the measurements
of Iris flowers categorized by their respective species.
 Your
objective is to train a machine learning model that can learn from
these measurements and accurately classify the Iris flowers into
their respective species.

Use the Iris dataset to develop a model that can classify iris
flowers into different species based on their sepal and petal
measurements. This dataset is widely used for introductory
classification tasks.
processing steps:-
========================
1) importing required libraries.

2) Exploring the Credit Card Fraud dataset.

3) Data preprocessing.

In [5]:
import numpy as np
import pandas as pd
from sklearn.decomposition import PCA
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
print("installation successfully completed")

installation successfully completed


In [6]:
class SVDPCA:
    def __init__(self, n_components=None):
        self.n_components = n_components

    @staticmethod
    def svd_flip_vector(U):
        max_abs_cols_U = np.argmax(np.abs(U), axis=0)
        # extract the signs of the max absolute values
        signs_U = np.sign(U[max_abs_cols_U, range(U.shape[1])])

        return U * signs_U

    def fit_transform(self, X):
        n_samples, n_features = X.shape
        X_centered = X - X.mean(axis=0)

        if self.n_components is None:
            self.n_components = min(n_samples, n_features)

        U, S, Vt = np.linalg.svd(X_centered)
        # flip the eigenvector sign to enforce deterministic output
        U_flipped = self.svd_flip_vector(U)

        self.explained_variance = (S[:self.n_components] ** 2) / (n_samples - 1)
        self.explained_variance_ratio = self.explained_variance / np.sum(self.explained_variance)

        # X_new = X * V = U * S * Vt * V = U * S
        X_transformed = U_flipped[:, : self.n_components] * S[: self.n_components]

        return X_transformed

In [8]:
#Uploading a dataset
df_path = "/content/IRIS.csv"
iris_df = pd.read_csv(df_path)
X, y = iris_df.iloc[:, :-1], iris_df.iloc[:, -1]
y = pd.Series(LabelEncoder().fit_transform(y))
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=0)
print(iris_df)

     sepal_length  sepal_width  petal_length  petal_width         species
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]


Model training and evaluation of the obtained results:-
============================================================
The manual implementation showed identical scikit-learn results. As you can see, the first 2 main components explain almost 98% of the variance in the data which allows you to reduce the number of features by half without much loss of information. If the number of features were not 4 but several thousand or millions, then this would significantly reduce the training time of models without significant loss of accuracy (and sometimes with increased accuracy by reducing multicollinearity between features) what makes PCA and its alternatives an excellent addition to other algorithms.

In [10]:
#pca(Principal Component Analysis (PCA))
pca = SVDPCA()
X_transformed = pca.fit_transform(X)

print('transformed data', X_transformed[:10], '', sep='\n')
print('explained_variance', pca.explained_variance)
print('explained_variance_ratio', pca.explained_variance_ratio)

transformed data
[[-2.68420713e+00  3.26607315e-01 -2.15118370e-02  1.00615724e-03]
 [-2.71539062e+00 -1.69556848e-01 -2.03521425e-01  9.96024240e-02]
 [-2.88981954e+00 -1.37345610e-01  2.47092410e-02  1.93045428e-02]
 [-2.74643720e+00 -3.11124316e-01  3.76719753e-02 -7.59552741e-02]
 [-2.72859298e+00  3.33924564e-01  9.62296998e-02 -6.31287327e-02]
 [-2.27989736e+00  7.47782713e-01  1.74325619e-01 -2.71468037e-02]
 [-2.82089068e+00 -8.21045110e-02  2.64251085e-01 -5.00996251e-02]
 [-2.62648199e+00  1.70405349e-01 -1.58015103e-02 -4.62817610e-02]
 [-2.88795857e+00 -5.70798026e-01  2.73354061e-02 -2.66154143e-02]
 [-2.67384469e+00 -1.06691704e-01 -1.91533300e-01 -5.58909660e-02]]

explained_variance [4.22484077 0.24224357 0.07852391 0.02368303]
explained_variance_ratio [0.92461621 0.05301557 0.01718514 0.00518309]


In [11]:
# PCA (scikit-learn)
sk_pca = PCA()
sk_X_transformed = sk_pca.fit_transform(X)

print('sk transformed data', sk_X_transformed[:10], '', sep='\n')
print('sk explained_variance', sk_pca.explained_variance_)
print('sk explained_variance_ratio_', sk_pca.explained_variance_ratio_)

sk transformed data
[[-2.68420713e+00  3.26607315e-01 -2.15118370e-02  1.00615724e-03]
 [-2.71539062e+00 -1.69556848e-01 -2.03521425e-01  9.96024240e-02]
 [-2.88981954e+00 -1.37345610e-01  2.47092410e-02  1.93045428e-02]
 [-2.74643720e+00 -3.11124316e-01  3.76719753e-02 -7.59552741e-02]
 [-2.72859298e+00  3.33924564e-01  9.62296998e-02 -6.31287327e-02]
 [-2.27989736e+00  7.47782713e-01  1.74325619e-01 -2.71468037e-02]
 [-2.82089068e+00 -8.21045110e-02  2.64251085e-01 -5.00996251e-02]
 [-2.62648199e+00  1.70405349e-01 -1.58015103e-02 -4.62817610e-02]
 [-2.88795857e+00 -5.70798026e-01  2.73354061e-02 -2.66154143e-02]
 [-2.67384469e+00 -1.06691704e-01 -1.91533300e-01 -5.58909660e-02]]

sk explained_variance [4.22484077 0.24224357 0.07852391 0.02368303]
sk explained_variance_ratio_ [0.92461621 0.05301557 0.01718514 0.00518309]


Cons:

the inevitable loss of some information in the data;
search only for linear dependence in the data (in the classic PCA);
the lack of semantic meaning of the main components due to the difficulty of linking them with real features